#!/usr/bin/env python3
"""Derive the Mathematical Programming Computation version from the canonical manuscript.

Only the editorial frame changes: document class, front matter, abstract length, the position
of the declarations, the bibliography style and three tables scaled to the narrower Springer
measure. The body is copied verbatim, so a diff against paper/main.tex shows exactly what the
journal format required. See paper/mpc/MPC_NOTES.md.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "paper/main.tex"
OUT = ROOT / "paper/mpc/main_mpc.tex"
ABSTRACT = ROOT / "paper/mpc/abstract.tex"

PREAMBLE = r"""%% Mathematical Programming Computation (Springer) submission version.
%% Generated by scripts/research/build_mpc.py from paper/main.tex: the body is identical and
%% only the editorial frame differs. See paper/mpc/MPC_NOTES.md for the list of changes.
\RequirePackage{fix-cm}
%% envcountsect and envcountsame reproduce the numbering of the original manuscript:
%% one shared counter, numbered within the section (Proposition 4.1, 4.2, ..., Corollary 5.2).
\documentclass[smallextended,envcountsect,envcountsame]{svjour3}
\smartqed
\journalname{Mathematical Programming Computation}
\usepackage[T1]{fontenc}
\usepackage{microtype}
\usepackage{amsmath,amssymb,mathtools}
\usepackage{graphicx,booktabs,tabularx,array,enumitem}
\usepackage[numbers,sort&compress]{natbib}
\usepackage{xurl}
\usepackage[hidelinks]{hyperref}
\usepackage[capitalise,nameinlink,noabbrev]{cleveref}
%% The class defines the theorem-like environments itself, and with envcountsame they all share
%% the "theorem" counter, which is what cleveref keys on. Every theorem-like environment in this
%% paper is a proposition except one corollary, which is never cross-referenced, so naming that
%% counter "Proposition" reproduces the wording of the original manuscript exactly. If a theorem
%% or a reference to the corollary is ever added, this has to be revisited.
\crefname{theorem}{Proposition}{Propositions}
\Crefname{theorem}{Proposition}{Propositions}
\newcommand{\doi}[1]{\href{https://doi.org/#1}{\nolinkurl{https://doi.org/#1}}}
\newcommand{\R}{\mathbb R}
\newcommand{\diag}{\operatorname{diag}}
\newcommand{\norm}[1]{\left\lVert#1\right\rVert}
\newcommand{\abs}[1]{\left|#1\right|}
\newcommand{\argmin}{\operatorname*{arg\,min}}
\newcommand{\nnz}{\operatorname{nnz}}
\graphicspath{{figs/}}
%% The Springer measure is narrower than the original layout; a little stretch absorbs the
%% lines that no longer break as well. No text is changed.
\emergencystretch=1.5em
\begin{document}

\title{Pre-Export Row Scaling for Generated Mixed-Integer Programs: Mechanism Attribution and
Residual-Budget Contracts}
\titlerunning{Pre-Export Row Scaling for Generated MIPs}
\author{Mathias Rodr\'iguez Castro}
\authorrunning{M. Rodr\'iguez Castro}
\institute{M. Rodr\'iguez Castro \at
              Facultad de Ingenier\'ia, Universidad de la Rep\'ublica,
              Montevideo, Uruguay \\
              \email{mathiasr@fing.edu.uy}}
\date{Received: date / Accepted: date}
\maketitle

\begin{abstract}
%%ABSTRACT%%
\keywords{Mixed-integer linear programming \and Row scaling \and Numerical reliability \and
Equilibration \and Residual budgets \and Computational reproducibility}
%% MSC 2020, checked against the AMS list (mathscinet.ams.org/msnhtml/msc2020.pdf):
%% 90C11 Mixed integer programming; 65F35 Numerical computation of matrix norms, conditioning,
%% scaling; 90-08 Computational methods for problems pertaining to operations research and
%% mathematical programming; 65G50 Roundoff error.
\subclass{90C11 \and 65F35 \and 90-08 \and 65G50}
\end{abstract}
"""

WIDE_TABLES = ["fixed-basis", "budget-paired", "application-budget"]


def main():
    src = SRC.read_text()
    body = src[src.index("\\section{Introduction}"):]

    declarations = body[body.index("\\section*{Statements and Declarations}"):
                        body.index("\\section*{Supplementary information}")].rstrip() + "\n"
    body = body.replace(declarations + "\n", "").replace(declarations, "")

    body = body.replace("""\\bibliographystyle{plainnat}
\\bibliography{research-references}
\\end{document}""",
"""\\bibliographystyle{spmpsci}
\\bibliography{research-references}

""" + declarations + """
\\end{document}""")

    # The Springer text block is narrower; the wide tables are scaled to fit it. Content,
    # alignment and numbers are untouched.
    for name in WIDE_TABLES:
        a = "\\input{tables/%s}" % name
        assert body.count(a) == 1, name
        body = body.replace(a, "\\resizebox{\\textwidth}{!}{\\input{tables/%s}}" % name, 1)

    OUT.write_text(PREAMBLE.replace("%%ABSTRACT%%", ABSTRACT.read_text().strip()) + "\n" + body)
    print("wrote", OUT.relative_to(ROOT), OUT.read_text().count("\n"), "lines")


if __name__ == "__main__":
    main()
